#!/bin/sh
set -eu

APPDIR="${APPDIR:-$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)}"

export PATH="${APPDIR}/usr/bin:${PATH}"
export XDG_DATA_DIRS="${APPDIR}/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas"
export GTK_EXE_PREFIX="${APPDIR}/usr"
export GTK_DATA_PREFIX="${APPDIR}/usr"

exec "${APPDIR}/usr/bin/parfait" "$@"
